//
//  MovieWorker.swift
//  movieList
//
//  Created by Erva Hatun Tekeoğlu on 13.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation
import Alamofire

protocol MovieListWorkerProtocol {
    func fetchMovies(completionHandler:@escaping (() throws -> MovieResponseModel) -> Void)
}

class MovieWorker {
    
    var worker: MovieListWorkerProtocol
    
    init(_ worker: MovieListWorkerProtocol){
        self.worker = worker
    }
    
    func fetchMovies(completionHandler: @escaping ((_ response: MovieResponseModel, Error?) -> Void)) {
        self.worker.fetchMovies( completionHandler:{ (result: () throws -> MovieResponseModel) -> Void in
            do {
                let result = try result()
                NSLog("Movies downloaded!")
                completionHandler(result,nil)
            }catch let error{
                NSLog("Error trying to get movies in network \(error.localizedDescription)")
                print(error)
            }

        })
    }
}
