//
//  MovieViewController.swift
//  movieList
//
//  Created by Erva Hatun Tekeoğlu on 13.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol MovieDisplayLogic: class {
    func displayFetchMovies(viewModel: Movie.FetchMovie.ViewModel)
    func displayMovieDetail()
}

class MovieViewController: UIViewController, MovieDisplayLogic {
    @IBOutlet weak var tableView: UITableView!
    
    var interactor: MovieBusinessLogic?
    var router: (NSObjectProtocol & MovieRoutingLogic & MovieDataPassing)?

    // MARK: Object lifecycle
      
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
      
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
      
    // MARK: Setup
      
    private func setup() {
        let viewController = self
        let interactor = MovieInteractor()
        let presenter = MoviePresenter()
        let router = MovieRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
      
      // MARK: Routing
      
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
            router.perform(selector, with: segue)
            }
        }
    }
      
      // MARK: View lifecycle
      
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchMovies()
        tableView.delegate = self
        tableView.dataSource = self
    }
      
      // MARK: Do something
        
    var displayedMovies: [Movie.FetchMovie.ViewModel.DisplayedMovies] = []
      //@IBOutlet weak var nameTextField: UITextField!
      
    func fetchMovies() {
        let request = Movie.FetchMovie.Request()
        interactor?.fetchMovies(request: request)
    }
      
    func displayFetchMovies(viewModel: Movie.FetchMovie.ViewModel){
        displayedMovies = viewModel.displayedMovies
        tableView.isHidden = false
        tableView.reloadData()
        //nameTextField.text = viewModel.name
    }
    
    func displayMovieDetail() {
        router?.routeToMovieDetail(segue: nil)
    }
}

extension MovieViewController:  UITableViewDelegate, UITableViewDataSource {
    // MARK: - Table view data source
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedMovies.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let displayedMovie = displayedMovies[indexPath.row]
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "MovieTableViewCell") as? MovieTableViewCell else {
            return UITableViewCell()
        }
        
        cell.movieTitle.text = displayedMovie.originalTitle
        let imageUrl = "http://image.tmdb.org/t/p/w500\(displayedMovie.posterPath)"
        cell.movieImage.kf.setImage(with: URL(string: imageUrl))
        cell.releaseDate.text = displayedMovie.releaseDate
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        displayMovieDetail()
    }
}
