//
//  MovieInteractor.swift
//  movieList
//
//  Created by Erva Hatun Tekeoğlu on 13.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieBusinessLogic {
  func fetchMovies(request: Movie.FetchMovie.Request)
}

protocol MovieDataStore {
    var movies: MovieResponseModel? { get }
}

class MovieInteractor: MovieBusinessLogic, MovieDataStore {
    var movies: MovieResponseModel?
    var presenter: MoviePresentationLogic?
    var worker: MovieWorker? = MovieWorker(MovieNetworkWorker())
    
    // MARK: Do something
    func fetchMovies(request: Movie.FetchMovie.Request) {
        worker?.fetchMovies(completionHandler: { result, error in
            if error == nil {
                self.movies = result
                let response = Movie.FetchMovie.Response(movies: result)
                self.presenter?.presentMovies(response: response)
            }
        })
    }
}
