//
//  MovieDetailPresenter.swift
//  MovieList
//
//  Created by Erva Hatun Tekeoğlu on 20.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic
{
  func presentSomething(response: MovieDetail.Something.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic
{
  weak var viewController: MovieDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MovieDetail.Something.Response)
  {
    let viewModel = MovieDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
