//
//  MovieDetailPresenter.swift
//  MovieList
//
//  Created by Erva Hatun Tekeoğlu on 20.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic
{
  func presentMovieDetail(response: MovieDetail.Movie.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic
{
  weak var viewController: MovieDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentMovieDetail(response: MovieDetail.Movie.Response)
  {
    let displayedMovie = MovieDetail.Movie.ViewModel.DisplayedMovie(originalTitle: response.movie.originalTitle, overview: response.movie.overview, posterPath: response.movie.posterPath, releaseDate: response.movie.releaseDate, title: response.movie.title)
    
    let viewModel = MovieDetail.Movie.ViewModel(displayedMovie: displayedMovie)
    viewController?.displayMovieDetail(viewModel: viewModel)
  }
}
