//
//  MovieDetailInteractor.swift
//  MovieList
//
//  Created by Erva Hatun Tekeoğlu on 20.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic
{
  func doSomething(request: MovieDetail.Something.Request)
}

protocol MovieDetailDataStore
{
  //var name: String { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore
{
  var presenter: MovieDetailPresentationLogic?
  var worker: MovieDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MovieDetail.Something.Request)
  {
    worker = MovieDetailWorker()
    worker?.doSomeWork()
    
    let response = MovieDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
