//
//  MovieDetailModels.swift
//  MovieList
//
//  Created by Erva Hatun Tekeoğlu on 20.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
  // MARK: Use cases
  
  enum Movie {
    struct Request {
    }
    struct Response {
        var movie: Result
    }
    struct ViewModel {
        struct DisplayedMovie {
            var originalTitle: String
            var overview: String
            var posterPath: String
            var releaseDate: String
            var title: String
        }
        
        var displayedMovie: DisplayedMovie
    }
  }
}

